[package]
name = "projector"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version="^4.5.0", features =["derive"]}
git2 = "0.20.2"
serde = "1.0.219"
serde_yaml = "0.9.34"
uuid = { version = "1.18.1", features = ["v4"] }
